export const FETCHING_DATA = 'FETCHING_DATA'

export const SUCCESS_RECEIVED_DATA = 'SUCCESS_RECEIVE_DATA'

export const FAILURE_RECEIVE_DATA = 'FAILURE_RECEIVE_DATA'

export const UPDATE_X_INDEX = 'UPDATE_X_INDEX'

export const UPDATE_Y_INDEX = 'UPDATE_Y_INDEX'

